services:
  - type: web
    name: urlshortener-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        fromDatabase:
          name: urlshortener-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
      - key: BACKEND_URL
        value: https://urlshortener-backend.onrender.com

databases:
  - name: urlshortener-db
    databaseName: urlshortener
    user: urlshortener
    plan: free
